@startuml
title Регистрация и ремонт дефекта

start

:Сообщение о новом дефекте (оператор);

if (Есть ли ремонтная зона со свободным ремонтным местом?) then (Да)
else (Нет)
    repeat
        :Ожидание освобождения ремонтной зоны;
    repeat while (ремонтная зона не стала свободной) is (Нет)
endif

:Диспетчер направляет автомобиль в свободную ремонтную зону;

if (Есть ли доступный рабочий в прикриплённой бригаде?) then (Да)
else (Нет)
    repeat
        :Ожидание освобождения рабочего;
    repeat while (рабочий не стал свободным) is (Нет)
endif

:Бригадир назначает ремонт конкретному рабочему на конкретном ремонтном месте;

fork
    :Ремонтник регистрирует дефект;
    :Фиксация времени начала ремонта, рабочего и ремонтного места;
fork again
    :Ремонтник начинает ремонт;
end fork

if (Ремонт выполнен?) then (Да)
else (Нет)
    repeat
        :Анализ причин невыполнения ремонта;
        :Корректирующие действия;
    repeat while (Ремонт не выполнен?) is (Нет)
endif

fork
    :Фиксация времени окончания ремонта;
fork again
    :Автомобиль возвращается на конвейер/в зону тестирования;
end fork
stop

@enduml
