@startuml
component База_данных as "База данных"
component Система_учёта_дефектов as "Система учёта дефектов"
component Модуль_отчётности as "Модуль отчётности"
component API as "API"
component Интерфейс_диспетчера as "Интерфейс диспетчера"
component Интерфейс_бригадира as "Интерфейс бригадира"
component Интерфейс_ремонтника as "Интерфейс ремонтника"
component Интерфейс_отдела_контроля_качества as "Интерфейс отдела контроля качества"
component Интерфейс_начальника_цеха as "Интерфейс начальника цеха"
component Интерфейс_бухгалтерии as "Интерфейс бухгалтерии"


Система_учёта_дефектов *-- Модуль_отчётности : содержит
Система_учёта_дефектов -- API : использует
API -- Интерфейс_диспетчера : обслуживает
API -- Интерфейс_ремонтника : обслуживает
API -- Интерфейс_бригадира : обслуживает
API -- Интерфейс_отдела_контроля_качества : обслуживает
API -- Интерфейс_начальника_цеха : обслуживает
API -- Интерфейс_бухгалтерии : обслуживает
Система_учёта_дефектов o-- База_данных : использует

@enduml
