@startuml
state OFF as "Выключен"
state HEATING as "Нагревается"
state READY as "Готов к использованию"
state COOLING as "Охлаждается"

[*] --> OFF
OFF --> HEATING : Включить
HEATING --> READY : Достигнута температура
READY --> COOLING : Выключить нагрев
COOLING --> [*] : Охлажден
HEATING --> COOLING : Выключить нагрев
@enduml

